Ограничил ширину окна попапа
Danilok95432/t6-simple-admin pull request #1
Opened 2024-12-23 13:53 UTC by VMachihin

2024-12-24 05:53 UTC, Danilok95432 requested changes

2024-12-24 05:53 UTC, Danilok95432 commented on src/modals/auth-modal/index.module.scss
> +    width: 65vw;
Сделай вместо твоего media другое с max-width: 590px пусть будет 85vw, а то слишком узкое окно на телефонных разрешениях

2024-12-24 05:53 UTC, Danilok95432 commented on src/modals/auth-modal/index.module.scss
> +  // @media (max-width: 1440px) {
Комменты убери из кода

2024-12-24 05:53 UTC, Danilok95432 commented on src/modals/pass-recovery-modal/index.module.scss
> +    width: 65vw;
тут то же самое сделай. окно в принципе вообще использоваться не будет вот это, но пусть будет на всякий

2024-12-29 00:44 UTC, VMachihin commented on src/modals/auth-modal/index.module.scss
> +  // @media (max-width: 1440px) {
Сделал

2024-12-29 00:44 UTC, VMachihin commented on src/modals/auth-modal/index.module.scss
> +    width: 65vw;
Сделал

2024-12-29 00:44 UTC, VMachihin commented on src/modals/pass-recovery-modal/index.module.scss
> +    width: 65vw;
Сделал

2025-01-09 07:42 UTC, merged